name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Deploy to Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avr -e "ssh -i private_key -o StrictHostKeyChecking=no" . $USER@$HOST:/var/www/daily-activity
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST "cd /var/www/daily-activity && composer install && php artisan migrate --force"
