name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          rsync -avz --exclude='node_modules' --exclude='.git' -e "ssh -i private_key -o StrictHostKeyChecking=no" ./ $USER@$HOST:/var/www/daily-activity

      - name: Install dependencies
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i private_key $USER@$HOST -o StrictHostKeyChecking=no << 'EOF'
            cd /var/www/daily-activity
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run production
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan optimize
          EOF
